---
- hosts: localhost
  connection: local
  become: no
  gather_facts: no
  tasks:
   - name: Install package on production
     yum: 
       name: sos
       state: present
     when: {{ ansible_local['preferences']['general']['production'] }} == true
