---
- hosts: all
  gather_facts: true
  tasks:
   - name: Install package on production
     yum: 
       name: sos
       state: present
     when: "{{ ansible_local['preferance']['general']['production'] }} == true"
