---
- hosts: all
  deprecation_warnings: False
  gather_facts: true
  tasks:
   - name: Install package on production
     yum: 
       name: sos
       state: present
     when: "{{ ansible_local['preferance']['general']['production'] }} == true"

   - name: Remove package from non prod 
     yum:
       name: sos
       state: absent
     when: "{{ ansible_local['preferance']['general']['production'] }} == false"

   - name: Install once then stop
     yum:
       name: telnet
       state: present
     run_once: true
