---
- name: This is the root play
  hosts: all
  gather_facts: false
  tasks:
   - name: List all files in root
     command: "ls /root"
     register: rootout

   - name: Debug roott
     ansible.builtin.debug:
       var: rootout

   - name: Debug CMD
     ansible.builtin.debug:
       var: rootout.cmd

   - name: Debug Ansible inter
     ansible.builtin.debug:
       var: rootout.ansible_facts

   - name: This is not the play, it is the task name
     debug: 
       msg: "{{ ansible_play_name }}"
